title = "Elvish Shell"
author = "Qi Xiao"
feedPosts = 10
template = "template.html"
baseCSS = ["reset.css", "style.css", "icon-font.css", "sgr.css"]
rootURL = "https://elv.sh"

[index]
name = "home"
extraCSS = ["home/home.css"]

[[categories]]
name = "get"
title = "Get Elvish"

[[categories]]
name = "learn"
title = "Learn Elvish"

[[categories]]
name = "ref"
title = "Elvish Reference"

[[categories]]
name = "blog"
title = "Elvish Blog"

[[categories]]
name = "sponsor"
title = "Sponsoring Elvish's Development"
navHTML = "<span class='sponsor'></span>"
